// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WizardIndexImport } from './routes/wizard/index'

// Create/Update Routes

const WizardIndexRoute = WizardIndexImport.update({
  path: '/wizard/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard/': {
      preLoaderRoute: typeof WizardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([WizardIndexRoute])
